[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.101.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
